import type { Plan } from '@/types';

const ALL_STATES = [
  'AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA',
  'KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ',
  'NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT',
  'VA','WA','WV','WI','WY',
];

const MOST_STATES = ALL_STATES.filter((s) => !['NY','NJ','MA','VT'].includes(s));

export const PLANS: Plan[] = [
  // ── Short Term Medical ──────────────────────────────────────────────────
  {
    id: 'stm-basic',
    category: 'short-term-medical',
    name: 'BlueStar Basic',
    carrier: 'BlueStar Health',
    tier: 'basic',
    monthlyPremium: 89,
    annualDeductible: 5000,
    rating: 4.1,
    reviewCount: 312,
    tagline: 'Affordable bridge coverage for healthy individuals.',
    highlights: ['Doctor visits', 'Urgent care', 'Emergency room'],
    benefits: [
      { label: 'Primary care visits', value: '$30 copay', included: true },
      { label: 'Urgent care', value: '$75 copay', included: true },
      { label: 'Emergency room', value: '20% after deductible', included: true },
      { label: 'Hospitalization', value: '20% after deductible', included: true },
      { label: 'Prescription drugs', value: 'Not covered', included: false },
      { label: 'Mental health', value: 'Not covered', included: false },
    ],
    coinsurance: '80/20',
    maxBenefit: '$250,000 per term',
    availableStates: MOST_STATES,
  },
  {
    id: 'stm-standard',
    category: 'short-term-medical',
    name: 'BlueStar Standard',
    carrier: 'BlueStar Health',
    tier: 'standard',
    monthlyPremium: 149,
    annualDeductible: 2500,
    rating: 4.4,
    reviewCount: 541,
    tagline: 'Balanced coverage with lower out-of-pocket costs.',
    highlights: ['Rx coverage included', 'Mental health', 'Specialist visits'],
    popular: true,
    badge: 'Most Popular',
    benefits: [
      { label: 'Primary care visits', value: '$25 copay', included: true },
      { label: 'Urgent care', value: '$60 copay', included: true },
      { label: 'Emergency room', value: '20% after deductible', included: true },
      { label: 'Hospitalization', value: '20% after deductible', included: true },
      { label: 'Prescription drugs', value: 'Tier 1–3 covered', included: true },
      { label: 'Mental health', value: '10 visits/year', included: true },
    ],
    coinsurance: '80/20',
    maxBenefit: '$500,000 per term',
    availableStates: MOST_STATES,
  },
  {
    id: 'stm-premium',
    category: 'short-term-medical',
    name: 'BlueStar Premium',
    carrier: 'BlueStar Health',
    tier: 'premium',
    monthlyPremium: 219,
    annualDeductible: 1000,
    rating: 4.7,
    reviewCount: 289,
    tagline: 'Comprehensive short-term coverage rivaling major medical.',
    highlights: ['Low deductible', 'Full Rx', 'Maternity care'],
    benefits: [
      { label: 'Primary care visits', value: '$20 copay', included: true },
      { label: 'Urgent care', value: '$50 copay', included: true },
      { label: 'Emergency room', value: '10% after deductible', included: true },
      { label: 'Hospitalization', value: '10% after deductible', included: true },
      { label: 'Prescription drugs', value: 'All tiers covered', included: true },
      { label: 'Mental health', value: 'Unlimited visits', included: true },
    ],
    coinsurance: '90/10',
    maxBenefit: '$1,000,000 per term',
    availableStates: MOST_STATES,
  },
  {
    id: 'stm-bridge',
    category: 'short-term-medical',
    name: 'PrimeCare Bridge',
    carrier: 'PrimeCare Insurance',
    tier: 'standard',
    monthlyPremium: 129,
    annualDeductible: 3000,
    rating: 4.2,
    reviewCount: 198,
    tagline: 'Flexible coverage with nationwide access.',
    highlights: ['No network restriction', 'Telehealth included', 'Fast approval'],
    benefits: [
      { label: 'Primary care visits', value: '$35 copay', included: true },
      { label: 'Urgent care', value: '$70 copay', included: true },
      { label: 'Emergency room', value: '20% after deductible', included: true },
      { label: 'Hospitalization', value: '20% after deductible', included: true },
      { label: 'Prescription drugs', value: 'Tier 1 generics only', included: true },
      { label: 'Mental health', value: 'Not covered', included: false },
    ],
    coinsurance: '80/20',
    maxBenefit: '$500,000 per term',
    availableStates: MOST_STATES,
  },

  // ── Hospital Indemnity ──────────────────────────────────────────────────
  {
    id: 'hi-essential',
    category: 'hospital-indemnity',
    name: 'MedGuard Essential',
    carrier: 'MedGuard Life',
    tier: 'basic',
    monthlyPremium: 35,
    rating: 4.2,
    reviewCount: 204,
    tagline: 'Essential hospital cash benefits at a low monthly cost.',
    highlights: ['$200/day hospital benefit', 'ICU benefit', 'Same-day surgery'],
    benefits: [
      { label: 'Daily hospital benefit', value: '$200/day', included: true },
      { label: 'ICU benefit', value: '$400/day', included: true },
      { label: 'Surgery benefit', value: '$500 lump sum', included: true },
      { label: 'Ambulance', value: '$150/trip', included: true },
      { label: 'ER visit', value: '$100 per visit', included: false },
      { label: 'Recovery benefit', value: 'Not included', included: false },
    ],
    maxBenefit: '$200/day, up to 365 days',
    availableStates: ALL_STATES,
  },
  {
    id: 'hi-plus',
    category: 'hospital-indemnity',
    name: 'MedGuard Plus',
    carrier: 'MedGuard Life',
    tier: 'standard',
    monthlyPremium: 65,
    rating: 4.5,
    reviewCount: 387,
    tagline: 'Enhanced hospital benefits with ER and recovery coverage.',
    highlights: ['$400/day hospital', 'ER benefit', 'Recovery care'],
    popular: true,
    badge: 'Best Value',
    benefits: [
      { label: 'Daily hospital benefit', value: '$400/day', included: true },
      { label: 'ICU benefit', value: '$800/day', included: true },
      { label: 'Surgery benefit', value: '$1,000 lump sum', included: true },
      { label: 'Ambulance', value: '$200/trip', included: true },
      { label: 'ER visit', value: '$200 per visit', included: true },
      { label: 'Recovery benefit', value: '$100/day (up to 30 days)', included: true },
    ],
    maxBenefit: '$400/day, up to 365 days',
    availableStates: ALL_STATES,
  },
  {
    id: 'hi-elite',
    category: 'hospital-indemnity',
    name: 'MedGuard Elite',
    carrier: 'MedGuard Life',
    tier: 'premium',
    monthlyPremium: 95,
    rating: 4.7,
    reviewCount: 156,
    tagline: 'Maximum hospital cash protection for complete peace of mind.',
    highlights: ['$700/day hospital', 'Wellness benefit', 'Critical care rider'],
    benefits: [
      { label: 'Daily hospital benefit', value: '$700/day', included: true },
      { label: 'ICU benefit', value: '$1,400/day', included: true },
      { label: 'Surgery benefit', value: '$2,000 lump sum', included: true },
      { label: 'Ambulance', value: '$300/trip', included: true },
      { label: 'ER visit', value: '$350 per visit', included: true },
      { label: 'Recovery benefit', value: '$200/day (up to 60 days)', included: true },
    ],
    maxBenefit: '$700/day, up to 365 days',
    availableStates: ALL_STATES,
  },

  // ── Cancer Plans ───────────────────────────────────────────────────────
  {
    id: 'cancer-core',
    category: 'cancer',
    name: 'ShieldCare Core',
    carrier: 'ShieldCare Insurance',
    tier: 'basic',
    monthlyPremium: 28,
    rating: 4.0,
    reviewCount: 167,
    tagline: 'Essential cancer financial protection.',
    highlights: ['$10,000 diagnosis benefit', 'Chemo coverage', 'Radiation coverage'],
    benefits: [
      { label: 'Cancer diagnosis benefit', value: '$10,000 lump sum', included: true },
      { label: 'Chemotherapy', value: '$500/treatment', included: true },
      { label: 'Radiation therapy', value: '$300/treatment', included: true },
      { label: 'Surgery benefit', value: '$2,000', included: true },
      { label: 'Transportation', value: 'Not included', included: false },
      { label: 'Survivor benefit', value: 'Not included', included: false },
    ],
    waitingPeriod: '30 days',
    availableStates: ALL_STATES,
  },
  {
    id: 'cancer-extended',
    category: 'cancer',
    name: 'ShieldCare Extended',
    carrier: 'ShieldCare Insurance',
    tier: 'standard',
    monthlyPremium: 52,
    rating: 4.4,
    reviewCount: 312,
    tagline: 'Comprehensive cancer coverage with transportation benefits.',
    highlights: ['$25,000 diagnosis benefit', 'Transportation', 'Lodging'],
    popular: true,
    badge: 'Most Popular',
    benefits: [
      { label: 'Cancer diagnosis benefit', value: '$25,000 lump sum', included: true },
      { label: 'Chemotherapy', value: '$1,000/treatment', included: true },
      { label: 'Radiation therapy', value: '$600/treatment', included: true },
      { label: 'Surgery benefit', value: '$5,000', included: true },
      { label: 'Transportation', value: '$0.22/mile', included: true },
      { label: 'Survivor benefit', value: '$2,500', included: true },
    ],
    waitingPeriod: '30 days',
    availableStates: ALL_STATES,
  },
  {
    id: 'cancer-comprehensive',
    category: 'cancer',
    name: 'ShieldCare Comprehensive',
    carrier: 'ShieldCare Insurance',
    tier: 'premium',
    monthlyPremium: 78,
    rating: 4.8,
    reviewCount: 98,
    tagline: 'Maximum cancer protection with return of premium.',
    highlights: ['$50,000 diagnosis benefit', 'Return of premium', 'Experimental treatment'],
    benefits: [
      { label: 'Cancer diagnosis benefit', value: '$50,000 lump sum', included: true },
      { label: 'Chemotherapy', value: '$2,000/treatment', included: true },
      { label: 'Radiation therapy', value: '$1,200/treatment', included: true },
      { label: 'Surgery benefit', value: '$10,000', included: true },
      { label: 'Transportation', value: '$0.22/mile, unlimited', included: true },
      { label: 'Survivor benefit', value: '$5,000', included: true },
    ],
    waitingPeriod: '30 days',
    availableStates: ALL_STATES,
  },

  // ── Dental Plans ───────────────────────────────────────────────────────
  {
    id: 'dental-preventive',
    category: 'dental',
    name: 'SmilePlan Preventive',
    carrier: 'SmilePlan Dental',
    tier: 'basic',
    monthlyPremium: 18,
    rating: 4.3,
    reviewCount: 521,
    tagline: 'Keep up with cleanings and check-ups affordably.',
    highlights: ['2 cleanings/year', 'X-rays included', 'No waiting period'],
    benefits: [
      { label: 'Preventive (cleanings, X-rays)', value: '100% covered', included: true },
      { label: 'Basic (fillings)', value: 'Not covered', included: false },
      { label: 'Major (crowns, root canals)', value: 'Not covered', included: false },
      { label: 'Orthodontia', value: 'Not covered', included: false },
      { label: 'Annual maximum', value: '$500', included: true },
      { label: 'Deductible', value: 'None', included: true },
    ],
    availableStates: ALL_STATES,
  },
  {
    id: 'dental-basic',
    category: 'dental',
    name: 'SmilePlan Basic',
    carrier: 'SmilePlan Dental',
    tier: 'standard',
    monthlyPremium: 32,
    rating: 4.5,
    reviewCount: 743,
    tagline: 'Complete preventive and basic restorative coverage.',
    highlights: ['Fillings covered', '$1,500 annual max', 'Large network'],
    popular: true,
    badge: 'Best Value',
    benefits: [
      { label: 'Preventive (cleanings, X-rays)', value: '100% covered', included: true },
      { label: 'Basic (fillings)', value: '80% after deductible', included: true },
      { label: 'Major (crowns, root canals)', value: 'Not covered', included: false },
      { label: 'Orthodontia', value: 'Not covered', included: false },
      { label: 'Annual maximum', value: '$1,500', included: true },
      { label: 'Deductible', value: '$50/year', included: true },
    ],
    availableStates: ALL_STATES,
  },
  {
    id: 'dental-full',
    category: 'dental',
    name: 'SmilePlan Full',
    carrier: 'SmilePlan Dental',
    tier: 'premium',
    monthlyPremium: 45,
    rating: 4.6,
    reviewCount: 412,
    tagline: 'Comprehensive dental care including major work and orthodontia.',
    benefits: [
      { label: 'Preventive (cleanings, X-rays)', value: '100% covered', included: true },
      { label: 'Basic (fillings)', value: '80% after deductible', included: true },
      { label: 'Major (crowns, root canals)', value: '50% after deductible', included: true },
      { label: 'Orthodontia', value: '50%, up to $1,500 lifetime', included: true },
      { label: 'Annual maximum', value: '$2,000', included: true },
      { label: 'Deductible', value: '$50/year', included: true },
    ],
    highlights: ['Crowns & root canals', 'Orthodontia included', '$2,000 annual max'],
    availableStates: ALL_STATES,
  },

  // ── Vision Plans ────────────────────────────────────────────────────────
  {
    id: 'vision-standard',
    category: 'vision',
    name: 'ClearView Standard',
    carrier: 'ClearView Vision',
    tier: 'basic',
    monthlyPremium: 8,
    rating: 4.2,
    reviewCount: 634,
    tagline: 'Affordable vision coverage for exams and eyewear.',
    highlights: ['Annual eye exam', '$150 frame allowance', '30,000+ providers'],
    benefits: [
      { label: 'Eye exam', value: '$10 copay, 1/year', included: true },
      { label: 'Frames', value: '$150 allowance, 1/year', included: true },
      { label: 'Contact lenses', value: '$130 allowance (in lieu of frames)', included: true },
      { label: 'Lens options', value: 'Standard lenses covered', included: true },
      { label: 'LASIK discount', value: '15% off', included: true },
      { label: 'Progressive lenses', value: 'Not covered', included: false },
    ],
    availableStates: ALL_STATES,
  },
  {
    id: 'vision-enhanced',
    category: 'vision',
    name: 'ClearView Enhanced',
    carrier: 'ClearView Vision',
    tier: 'standard',
    monthlyPremium: 14,
    rating: 4.6,
    reviewCount: 489,
    tagline: 'Enhanced vision benefits including progressives and higher allowances.',
    highlights: ['$250 frame allowance', 'Progressives covered', 'LASIK discount'],
    popular: true,
    badge: 'Most Popular',
    benefits: [
      { label: 'Eye exam', value: '$0 copay, 1/year', included: true },
      { label: 'Frames', value: '$250 allowance, 1/year', included: true },
      { label: 'Contact lenses', value: '$200 allowance (in lieu of frames)', included: true },
      { label: 'Lens options', value: 'Standard + progressives covered', included: true },
      { label: 'LASIK discount', value: '25-40% off', included: true },
      { label: 'Progressive lenses', value: 'Covered', included: true },
    ],
    availableStates: ALL_STATES,
  },
  {
    id: 'vision-premium',
    category: 'vision',
    name: 'ClearView Premium',
    carrier: 'ClearView Vision',
    tier: 'premium',
    monthlyPremium: 22,
    rating: 4.7,
    reviewCount: 201,
    tagline: 'Top-tier vision coverage with family benefits and LASIK.',
    highlights: ['$350 frame allowance', '2 exams/year', 'Anti-reflective included'],
    benefits: [
      { label: 'Eye exam', value: '$0 copay, 2/year', included: true },
      { label: 'Frames', value: '$350 allowance, 1/year', included: true },
      { label: 'Contact lenses', value: '$300 allowance', included: true },
      { label: 'Lens options', value: 'All lens types covered', included: true },
      { label: 'LASIK discount', value: '40% off', included: true },
      { label: 'Progressive lenses', value: 'Covered', included: true },
    ],
    availableStates: ALL_STATES,
  },

  // ── Prescription Plans ──────────────────────────────────────────────────
  {
    id: 'rx-generic',
    category: 'prescription',
    name: 'RxCare Generic',
    carrier: 'RxCare',
    tier: 'basic',
    monthlyPremium: 15,
    rating: 4.0,
    reviewCount: 287,
    tagline: 'Low-cost plan focused on generic medication savings.',
    highlights: ['$0 generics at select pharmacies', '60,000+ pharmacies', 'Mail order'],
    benefits: [
      { label: 'Tier 1 generics', value: '$0–$5 copay', included: true },
      { label: 'Tier 2 preferred brand', value: 'Not covered', included: false },
      { label: 'Tier 3 non-preferred', value: 'Not covered', included: false },
      { label: 'Specialty drugs', value: 'Not covered', included: false },
      { label: 'Mail order (90-day)', value: '$10 for generics', included: true },
      { label: 'Pharmacy network', value: '60,000+ locations', included: true },
    ],
    availableStates: ALL_STATES,
  },
  {
    id: 'rx-preferred',
    category: 'prescription',
    name: 'RxCare Preferred',
    carrier: 'RxCare',
    tier: 'standard',
    monthlyPremium: 28,
    rating: 4.4,
    reviewCount: 452,
    tagline: 'Generic and brand-name coverage for everyday medications.',
    highlights: ['Brand-name covered', 'Mail order savings', 'Drug price tool'],
    popular: true,
    badge: 'Best Value',
    benefits: [
      { label: 'Tier 1 generics', value: '$5 copay', included: true },
      { label: 'Tier 2 preferred brand', value: '$30 copay', included: true },
      { label: 'Tier 3 non-preferred', value: '$55 copay', included: true },
      { label: 'Specialty drugs', value: 'Not covered', included: false },
      { label: 'Mail order (90-day)', value: '2.5x copay', included: true },
      { label: 'Pharmacy network', value: '70,000+ locations', included: true },
    ],
    availableStates: ALL_STATES,
  },
  {
    id: 'rx-premier',
    category: 'prescription',
    name: 'RxCare Premier',
    carrier: 'RxCare',
    tier: 'premium',
    monthlyPremium: 45,
    rating: 4.6,
    reviewCount: 198,
    tagline: 'Full-tier coverage including specialty medications.',
    highlights: ['Specialty drugs covered', 'Lowest copays', 'CVS Caremark network'],
    benefits: [
      { label: 'Tier 1 generics', value: '$0 copay', included: true },
      { label: 'Tier 2 preferred brand', value: '$20 copay', included: true },
      { label: 'Tier 3 non-preferred', value: '$40 copay', included: true },
      { label: 'Specialty drugs', value: '$75 copay', included: true },
      { label: 'Mail order (90-day)', value: '2x copay', included: true },
      { label: 'Pharmacy network', value: '80,000+ locations', included: true },
    ],
    availableStates: ALL_STATES,
  },

  // ── Critical Illness ────────────────────────────────────────────────────
  {
    id: 'ci-basic',
    category: 'critical-illness',
    name: 'LifeShield Basic',
    carrier: 'LifeShield Insurance',
    tier: 'basic',
    monthlyPremium: 22,
    rating: 4.1,
    reviewCount: 178,
    tagline: 'Core critical illness protection with a $15,000 benefit.',
    highlights: ['$15,000 lump sum', 'Heart attack & stroke', 'Cash in 7 days'],
    benefits: [
      { label: 'Heart attack', value: '$15,000', included: true },
      { label: 'Stroke', value: '$15,000', included: true },
      { label: 'Major organ transplant', value: '$15,000', included: true },
      { label: 'End-stage renal failure', value: 'Not covered', included: false },
      { label: 'Cancer (internal)', value: 'Not covered', included: false },
      { label: 'Waiver of premium', value: 'Not included', included: false },
    ],
    waitingPeriod: '30 days',
    availableStates: MOST_STATES,
  },
  {
    id: 'ci-standard',
    category: 'critical-illness',
    name: 'LifeShield Standard',
    carrier: 'LifeShield Insurance',
    tier: 'standard',
    monthlyPremium: 44,
    rating: 4.5,
    reviewCount: 341,
    tagline: 'Expanded coverage including cancer and renal failure.',
    highlights: ['$30,000 lump sum', 'Cancer included', 'Waiver of premium'],
    popular: true,
    badge: 'Most Popular',
    benefits: [
      { label: 'Heart attack', value: '$30,000', included: true },
      { label: 'Stroke', value: '$30,000', included: true },
      { label: 'Major organ transplant', value: '$30,000', included: true },
      { label: 'End-stage renal failure', value: '$30,000', included: true },
      { label: 'Cancer (internal)', value: '$15,000 (50% benefit)', included: true },
      { label: 'Waiver of premium', value: 'Included', included: true },
    ],
    waitingPeriod: '30 days',
    availableStates: MOST_STATES,
  },
  {
    id: 'ci-premium',
    category: 'critical-illness',
    name: 'LifeShield Premium',
    carrier: 'LifeShield Insurance',
    tier: 'premium',
    monthlyPremium: 68,
    rating: 4.7,
    reviewCount: 127,
    tagline: 'Maximum critical illness protection with $50,000 benefit.',
    highlights: ['$50,000 lump sum', 'Full cancer benefit', 'Second occurrence rider'],
    benefits: [
      { label: 'Heart attack', value: '$50,000', included: true },
      { label: 'Stroke', value: '$50,000', included: true },
      { label: 'Major organ transplant', value: '$50,000', included: true },
      { label: 'End-stage renal failure', value: '$50,000', included: true },
      { label: 'Cancer (internal)', value: '$50,000 (full benefit)', included: true },
      { label: 'Waiver of premium', value: 'Included', included: true },
    ],
    waitingPeriod: '30 days',
    availableStates: MOST_STATES,
  },
];

export function getAllPlans(): Plan[] {
  return PLANS;
}

export function getPlansByCategory(category: string): Plan[] {
  return PLANS.filter((p) => p.category === category);
}

export function getPlanById(id: string): Plan | undefined {
  return PLANS.find((p) => p.id === id);
}

export function filterPlans(options: {
  categories?: string[];
  maxMonthly?: number;
  state?: string;
}): Plan[] {
  return PLANS.filter((p) => {
    if (options.categories?.length && !options.categories.includes(p.category)) return false;
    if (options.maxMonthly && p.monthlyPremium > options.maxMonthly) return false;
    if (options.state && !p.availableStates.includes(options.state)) return false;
    return true;
  });
}
